<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG0uNFxi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG0uNFxi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG0uNFxi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG0uNFxi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG0uNFxi\App_KernelDevDebugContainer([
    'container.build_hash' => 'G0uNFxi',
    'container.build_id' => 'ee387c18',
    'container.build_time' => 1702389689,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG0uNFxi');
